### ISSUE TITLE
Khadas Vim: OpenPHT does not boot.

### ISSUE THREAD

**Issue by eugene2878** [Veisen/OpenPHT#1]
OpenPHT logo comes up with following errors:
*** Error in mount_storage: mount_common: Could not mount LABEL=LIBREELEC_DISK ***
### Starting debugging shell... type exit to quit ###
ssh: can't access tty: job control turned off

**Comment by Veisen** [comment]
fixed in new release

**Comment by lucypjohn** [comment]
Is the source code on the 1.9 embedded page, the latest release? I get the exact same error after compiling
